require: rubocop-rails

Rails/FindBy:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true
  EnforcedStyle: aggressive

Rails/TimeZone:
  EnforcedStyle: flexible

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging
